[YUNIKORN-521] Placeholder pods are not cleaned when the job is deleted
apache/incubator-yunikorn-k8shim pull request #232
Opened 2021-02-19 15:37 UTC by kingamarton

Filled  ownreference field for the placeholder pods

2021-02-20 06:46 UTC, yangwwei requested changes
Can we add some UT in `general_test.go` ? that needs to cover the case where the pod has ownerReference and hasn't.

2021-02-20 06:46 UTC, yangwwei commented on pkg/appmgmt/general/general.go
> +		PlaceholderOwnerReferences: pod.OwnerReferences,
I think we can just call this owner reference since this is a general K8s concept.
It doesn't mean only placeholder pod has that.

2021-03-02 10:26 UTC, wilfred-s reviewed
Couple of small points more about style than code content.

2021-03-02 10:26 UTC, wilfred-s commented on pkg/cache/application.go
> +func (app *Application) setOwnReference(ref []metav1.OwnerReference) {
nit: can we name this `setOwnerReference()`

2021-03-02 10:26 UTC, wilfred-s commented on pkg/cache/placeholder.go
> +	ownerRef := app.placeholderOwnerReferences
nit: this is a list of references, should call this `ownerRefs` plural

2021-03-02 10:26 UTC, wilfred-s commented on pkg/cache/placeholder_manager_test.go
> +		assert.Assert(t, pod.OwnerReferences[0].UID == ownRef.UID, "The owner reference UID does not match")
nit should we not use `assert.Equals()` all comparisons are simple values?

2021-03-16 16:21 UTC, yangwwei commented on pkg/cache/placeholder.go
> +	}
we are setting the controller field to false all the time.
could you pls add some more comments why we are doing this?

2021-03-16 16:22 UTC, yangwwei commented on pkg/appmgmt/general/general.go
> +func getOwnerReferences(pod *v1.Pod) []metav1.OwnerReference {
pls add comments to this function, to explain how we decide what owner-reference will be set for the placeholders.

2021-03-16 18:25 UTC, yangwwei approved these changes
LGTM

2021-03-16 18:39 UTC, merged