[YUNIKORN-593]Optimize the UT for ListApplications
apache/incubator-yunikorn-k8shim pull request #378
Opened 2022-03-06 08:57 UTC by HuangTing-Yao

### What is this PR for?
Optimize the UT for ListApplications.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-593

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2022-03-06 08:58 UTC, HuangTing-Yao commented
I can move `podCase` array out of Test function, and turn on the lint check, if it is necessary.

2022-03-07 17:35 UTC, craigcondit requested changes
Looks good, with the exception of one typo I found.

2022-03-08 01:21 UTC, wilfred-s approved these changes
approved when the typo for the Templete gets fixed

2022-03-08 10:07 UTC, HuangTing-Yao commented on pkg/appmgmt/general/general_test.go
> +type Templete struct {
Fixed, Thanks.

2022-03-08 15:42 UTC, craigcondit approved these changes
+1 LGTM. Thanks @HuangTing-Yao for the contribution!

2022-03-08 15:43 UTC, closed without merging